require 'rails_helper'

RSpec.describe "Matrix", type: :system do
  describe "fields for A and B" do
    it "is generated by user input" do
      visit new_matrix_calculator_path

      fill_in 'row-A', with: 5
      fill_in 'column-A', with: 4

      fill_in 'row-B', with: 4
      fill_in 'column-B', with: 3

      click_button 'Generate Template'
      expect(page.has_field?('matrix_A-4-4')).to be true
      expect(page.has_field?('matrix_B-4-3')).to be true
      expect(page).to have_selector("input[type='number']", count: 32)
    end
  end
end
